### PR TITLE
chore(observation) [DAT-765]: Add observation_id to gene_centric and …

### PR DESCRIPTION
**Pull request by DrSpez**
…case_centric mappings

### CODE REVIEW

**Comment by junjun-zhang** [comment]
Do we have plan to add `consequence_id` into gene_centric and donor_centric indexes? It's currently in ssm_centric and ssm_occurrence_centric only.

**Comment by junjun-zhang** [comment]
This one will be merged, it's just about timing. The API/UI devs wish to have this ES mapping synchronized with what ES indexes use.

@DrSpez do you know whether the ES indexes to be used by UAT have this `observation_id` field in case_centric and gene_centric? How about `consequence_id` field?

**Comment by DrSpez** [comment]
This change has not made it to the UAT, no worries

**Comment by DrSpez** [comment]
@junjun-zhang yes, we should add `consequence_id` for sure! I will add a new pr for that

**Pull request closed without merging**
