### PR TITLE
nest slides directly under samples

### PR DESCRIPTION
**Pull request by cy**

### CODE REVIEW

**Comment by junjun-zhang** [comment]
Do we need it here as well: https://github.com/NCI-GDC/gdc-models/blob/master/es-models/case_centric/case_centric.mapping.yaml ?

**Comment by cy** [comment]
@junjun-zhang updated case_centric, didn't see samples there as well so added the whole samples structure, along with slide_ids and sample_ids (can see them in case_centric/_mapping)

**Comment by junjun-zhang** [comment]
@cy I was just asking, it actually not necessary to have any of the biospcimen related nodes in the 'viz' indexes. This is why the 'viz' indexes don't actually have 'sample' under it.

**Comment by junjun-zhang** [comment]
Close this, duplicated with #47

**Pull request closed without merging**
