### PR TITLE
Jbarno/kill symlinks

### PR DESCRIPTION
**Pull request by jbarno**
Dunno if this will work with mutation indexer, but its a mix of Christians changes and modifying setup to dynamically pull es-models without having to move it. 

Basically [this](https://stackoverflow.com/questions/4519127/setuptools-package-data-folder-location)

Also it will stop me from consistently doing the symlink loop when looking at this github page :)

### CODE REVIEW

**Comment by DrSpez** [comment]
Is it working?

**Comment by junjun-zhang** [comment]
Solution identified in #52. Closing this one.

**Comment by jbarno** [comment]
Actually we need this. Mutation indexer's version of pip really doesn't like the symlinks.

**Comment by jbarno** [comment]
Removing the symlink from the git repo, and moving it to be dynamic in setup.py. Works with older versions of pip.

**Pull request merged**
